- name: create manager servers
  hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ swarmsible_hetzner_manager_name_prefix | default('manager-') }}{{ item }}"
    server_type: "{{ swarmsible_hetzner_manager_server_type }}"
    image: "{{ swarmsible_hetzner_server_image }}"
    location: "{{ swarmsible_hetzner_server_location }}"
    ssh_keys: 
      - "{{ swarmsible_swarmsible_hetzner_ansible_root_ssh_key_name }}"
    labels:
      swarm_role: "manager"
    firewalls:
      - "swarm-servers"
    state: present
    enable_ipv6: "{{ swarmsible_nodes_enable_ipv6 | default(False) | bool }}"
  register: manager_servers
  with_sequence: start=1 end={{ swarmsible_hetzner_manager_count }}

- name: Attach managers to server network [default]
  hcloud_server_network:
    api_token: "{{ hcloud_token }}"
    network: "{{ swarmsible_hetzner_swarm_network_name }}"
    server: "{{ swarmsible_hetzner_manager_name_prefix | default('manager-') }}{{ item }}"
    ip: "192.168.1.{{ (item | int) + 1 }}"
    state: present
  with_sequence: start=1 end={{ swarmsible_hetzner_manager_count }}
  when: not swarmsible_hetzner_custom_private_network_enabled | default('False') | bool

- name: Attach managers to server network [custom private network]
  hcloud_server_network:
    api_token: "{{ hcloud_token }}"
    network: "{{ swarmsible_hetzner_swarm_network_name }}"
    server: "{{ swarmsible_hetzner_manager_name_prefix | default('manager-') }}{{ item }}"
    ip: "{{ swarmsible_hetzner_custom_private_network | ipsubnet(26, 1) | ipaddr((item | int) + 1) | ipaddr('address') }}"
    state: present
  with_sequence: start=1 end={{ swarmsible_hetzner_manager_count }}
  when: swarmsible_hetzner_custom_private_network_enabled | default('False') | bool