manager_count: 3
manager_server_type: cx21

worker_count: 5
worker_server_type: cx21

server_image: ubuntu-22.04
server_location: nbg1

swarm_lb_type: lb11
swarm_lb_certificate_name: "swarmlb-certs"
swarm_lb_certificate_domain_names: 
  - "*.mytest-swarm.nfcompose-cloud.de"
  - "*.mgmt.mytest-swarm.nfcompose-cloud.de"
swarm_lb_certificate_type: 'managed'

managers_part_of_lb: true

hetzner_ansible_ssh_key_name: ansible_root_rsa

hetzner_swarm_network_name: swarm_network