- name: "Create {{ hetzner_ansible_ssh_key_name }} ssh_key"
  hcloud_ssh_key:
    name: "{{ hetzner_ansible_ssh_key_name }}"
    public_key: "{{ lookup('ansible.builtin.file', playbook_dir + '/ssh_keys/root_rsa.pub') }}"
    state: present
    api_token: "{{ hcloud_token }}"
