- name: "Create networks [default]"
  when: not swarmsible_hetzner_custom_private_network_enabled | default('False') | bool
  block:
    - name: "Create {{ swarmsible_hetzner_swarm_network_name }} network"
      hcloud_network:
        api_token: "{{ hcloud_token }}"
        name: "{{ swarmsible_hetzner_swarm_network_name }}"
        ip_range: 192.168.0.0/16
        state: present

    - name: Create auxiliary subnetwork
      hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: "{{ swarmsible_hetzner_swarm_network_name }}"
        ip_range: 192.168.0.0/24
        network_zone: eu-central
        type: cloud
        state: present

    - name: Create manager subnetwork
      hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: "{{ swarmsible_hetzner_swarm_network_name }}"
        ip_range: 192.168.1.0/24
        network_zone: eu-central
        type: cloud
        state: present

    - name: Create worker subnetwork
      hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: "{{ swarmsible_hetzner_swarm_network_name }}"
        ip_range: 192.168.2.0/24
        network_zone: eu-central
        type: cloud
        state: present

- name: "Create networks [custom private network]"
  when: swarmsible_hetzner_custom_private_network_enabled | default('False') | bool
  block:
    - name: "Create {{ swarmsible_hetzner_swarm_network_name }} network"
      hcloud_network:
        api_token: "{{ hcloud_token }}"
        name: "{{ swarmsible_hetzner_swarm_network_name }}"
        ip_range: "{{ swarmsible_hetzner_custom_private_network }}"
        state: present

    - name: Create auxiliary subnetwork
      hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: "{{ swarmsible_hetzner_swarm_network_name }}"
        ip_range: "{{ swarmsible_hetzner_custom_private_network | ipsubnet(26, 0) }}"
        network_zone: eu-central
        type: cloud
        state: present

    - name: Create manager subnetwork
      hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: "{{ swarmsible_hetzner_swarm_network_name }}"
        ip_range: "{{ swarmsible_hetzner_custom_private_network | ipsubnet(26, 1) }}"
        network_zone: eu-central
        type: cloud
        state: present

    - name: Create worker subnetwork
      hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: "{{ swarmsible_hetzner_swarm_network_name }}"
        ip_range: "{{ swarmsible_hetzner_custom_private_network | ipsubnet(26, 2) }}"
        network_zone: eu-central
        type: cloud
        state: present