---

- name: setup swarm
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/hcloud_token.yml
    - vars/swarm_config.yml
  roles:
    - docker-swarm-hetzner-firewalls
    - docker-swarm-hetzner-networks
    - docker-swarm-hetzner-ssh-keys
    - docker-swarm-hetzner-manager-servers
    - docker-swarm-hetzner-worker-servers
    - docker-swarm-hetzner-loadbalancers

  
